
moduleName: example-b
teamNamespace: domain-a

sharedParams:
  ROOT_DIR: "namespaces/domain-a/projects/example-b"

defaultFileChangeTrigger: &defaultFileChangeTrigger
  - "namespaces/domain-a/projects/example-b/**"

onPullRequest:
  - name: build
    pipelineRef:
      name: common-job
    pipelineRunValues:
      params:
        COMMAND: make build
    triggerConditions:
      fileChangesMatchAny: *defaultFileChangeTrigger

  - name: test
    pipelineRef:
      name: common-job
    pipelineRunValues:
      params:
        COMMAND: make test
    triggerConditions:
      fileChangesMatchAny:
        - "namespaces/domain-a/projects/example-b/tests/test.sh"

onBranchMerge:
  - name: cleanup
    pipelineRef:
      name: common-job
    pipelineRunValues:
      params:
        COMMAND: >-
          make clean
    triggerConditions:
      destinationBranchMatchesAny:
        - 'main'
      fileChangesMatchAny: *defaultFileChangeTrigger
